# numpy.mean()

 Compute the **arithmetic mean** (*average*) along the specified axis.

- numpy.mean(a , axis=None , dtype=None)
- **a** : Input array or list.
- **axis** : (None or int or tuples of ints , optional)
    - None : means entire array (defult)
    - 0 : means along columns 
    - 1 : mean along rows 
- **dtype** (optional)
    - dtype for computation 

In [8]:
import numpy as np

In [9]:
# 1D array 
arr1 = np.array([1,2,3,4,5])
print(np.mean(arr1))

3.0


In [10]:
#2D array 
arr2 = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)
print(arr2)

[[1 2 3]
 [4 5 6]]


In [11]:
print("mean of entire array:")
print(np.mean(arr2))

mean of entire array:
3.5


In [12]:
# total columns = 3 
#[1,2,3]
#[4,5,6]

print("mean along columns: ")
print(np.mean(arr2,axis=0))

mean along columns: 
[2.5 3.5 4.5]


In [13]:
# total row = 2 

#[1,2,3]
#[4,5,6]

print("mean along rows:")
print(np.mean(arr2,axis=1))

mean along rows:
[2. 5.]
