In [8]:
import numpy as np

# np.eye() in the Numpy

**np.eye()** is a NumPy function used to create an **identity matrix**.

- All main diagonal elements are 1 and all other elements are 0.

**What is an Identity Matrix?**

- Square matrix

- Diagonal elements = 1

- Other elements = 0

### 3X3 
1 0 0\
0 1 0\
0 0 1


### np.eye(N) — Square identity matrix 

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### np.eye(N, M) — Rectangular identity-like matrix

In [11]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

### np.eye(N, M, k) — Shifted diagonal identity
- k = 0 → main diagonal

- k > 0 → above diagonal

- k < 0 → below diagonal

k decides where the 1s will appear — on the main diagonal, above it, or below it.

In [16]:
np.eye(3,3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [13]:
np.eye(3,3,k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])