## np.random.randint()
Generates random whole numbers (integers) betweeen a given range.
- low ≤ number < high

In [4]:
import numpy as np

In [ ]:
# Single random interger
print(np.random.randint(10))
#(0 to 9)
# ka beach ma kuch bhi

7


In [ ]:
# random intergers in range 
print(np.random.randint(5,15))
# generates a single random
# integer between
# 5 (included) and 15 (excluded)

11


In [ ]:
#1D array 
print(
np.random.randint(1,10,size=6)
)

[7 9 2 5 6 1]


In [ ]:
# 2D array 
#creating sample data for practice
print(
np.random.randint(1,10,size=(2,3))
    )

[[8 1 8]
 [9 3 1]]
