## np.arange()
used to create a squence of numbers with fixed step size.
- np.arange(start,stop,step)
- return numpy array

In [2]:
import numpy as np

np.arange(1,10,2)
# stop value is not included

array([1, 3, 5, 7, 9])

## np.random.rand()
Generated random decimal (float) numbers betweeen 0 and 1 
- 0 ≤ number < 1
### Syntex
- np.random.rand()
- np.random.rand(n)
- np.random.rand(rows, columns)

In [13]:
#single random number
# No parameter
print(np.random.rand())

0.2757347472839877


In [14]:
#1D array 
# One parameter
np.random.rand(5)
# Returns 5 random decimals (1D array)

array([0.98189637, 0.3740534 , 0.34710099, 0.61674031, 0.19347275])

In [ ]:
# #2D array (martrix)
# # Two parameters
# Returns 2 rows and 3 columns
np.random.rand(2,3)

array([[0.18845392, 0.42343418, 0.25167525],
       [0.14171137, 0.98828825, 0.16709758]])