## np.zeros()
Creates array filled with 0

In [13]:
import numpy as np

In [14]:
# create 1D Array 
np.zeros(5)
#shape (5,)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### When to use
- Initializing matrices
- Machine learning weights
- placeholder arrays

## np.ones()
Create array filled with 1

In [16]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### When to use
- Bias terms in ML
- Normalization tasks
- testing formulas

## np.full()
Create array with same custom value

In [17]:
np.full((2,2),10)

array([[10, 10],
       [10, 10]])

## np.eye()
Ones on specified diagonal and zeros elsewhere 
**(Identity matrix)**

In [18]:
# 3X3 identity matrix 
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
# 3X4 matrix with ones on main diagonal
print(np.eye(3,4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [20]:
#shift diagonal up by 1
print(np.eye(4,k=1))

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [21]:
#shift diagonal down by 2 
print(np.eye(5,k=-2))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
