## np.arange()
used to create a squence of numbers with fixed step size.
- np.arange(start,stop,step)
- return numpy array

In [18]:
import numpy as np

np.arange(1,10,2)
# stop value is not included

array([1, 3, 5, 7, 9])

## np.random.rand()
Generated random decimal (float) numbers betweeen 0 and 1 
- 0 ≤ number < 1
### Syntex
- np.random.rand()
- np.random.rand(n)
- np.random.rand(rows, columns)

In [19]:
#single random number
print(np.random.rand())

0.8435774854788204


In [20]:
#1D array 
np.random.rand(5)

array([0.1340466 , 0.84428966, 0.18190017, 0.12592978, 0.20731255])

In [21]:
#2D array (martrix)
np.random.rand(2,3)

array([[0.39200433, 0.57898453, 0.18485241],
       [0.54759387, 0.2246685 , 0.7808352 ]])